- .github/workflows/deploy-published-releases.yaml
> Fix release workflow

- README.md
> Fix logo URL

- README.md
Add icons and direct links to readme's top menu.
> Add icons and direct links to readme's top menu

- .github/workflows/branch-validations.yaml
- package.json
> Improve Github workflow

- .github/workflows/branch-validations.yaml
- .github/workflows/deploy-published-releases.yaml
- .github/workflows/release-drafter.yaml
> Add support for object subtype validation

- src/validation/objectType.ts
- test/validation/objectType.test.ts
Add support for object type validation.
> Add support for object type validation

- .eslintrc.json
- src/validation/functionType.ts
- test/validation/functionType.test.ts
Add support for function type validation.
> Add support for function type validation

- src/schema/loggerSchema.ts
- src/schema/sdkFacadeSchemas.ts
- src/schema/sdkSchemas.ts
- test/schemas/loggerSchema.test.ts
- test/schemas/sdkFacadeSchemas.test.ts
- test/schemas/sdkSchemas.test.ts
Add validation schema for loggers.
> Add validation schema for loggers

- src/schema/loggerSchema.ts
- test/schemas/loggerSchema.test.ts
Allow loggers to have extra members.
> Allow loggers to have extra members

- tsconfig.json
Export ES2015 modules to solve bundling issues with CommonJS.
> Export ES2015 modules to solve bundling issues with CommonJS

- src/eventManager.ts
- src/facade/sdkFacade.ts
- src/sdk.ts
- test/facade/sdkFacade.test.ts
- test/sdk.test.ts
> Cleanup SDK API

- src/container.ts
- src/retry/arbitraryPolicy.ts
- src/tracker.ts
- test/retry/arbitraryPolicy.test.ts
- test/tracker.test.ts
Decreases frequency of inactivity events.
Fixes #89
> Decreases frequency of inactivity events

- src/cookie.ts
- test/cookie.test.ts
Handle cases where the domain is undefined
> Handle cases where the domain is undefined

- .eslintrc.json
- src/channel/beaconSocketChannel.ts
- src/container.ts
- src/evaluator.ts
- src/facade/sdkFacade.ts
- src/json.ts
- src/logging/consoleLogger.ts
- src/sdkEvents.ts
- src/sourceLocation.ts
- src/tab.ts
- src/tracker.ts
- src/trackingEvents.ts
- test/cache/inMemoryCache.test.ts
- test/container.test.ts
- test/eventManager.test.ts
- test/sourceLocation.test.ts
Apply the recommendation spoted by [LGTM](https://lgtm.com/projects/g/croct-tech/sdk-js/snapshot/90e662a02edb07edcf61292ca1871402501190d6/files/src/sourceLocation.ts?sort=name&dir=ASC&mode=heatmap#x1da0d4c20a2cbb51:1).
> Fix missing semicolons

- src/schema/userSchema.ts
- src/trackingEvents.ts
- test/facade/trackerFacade.test.ts
- test/schemas/userSchema.test.ts
- test/tracker.test.ts
Add interests and activities to user profile schema.
> Add interests and activities to user profile schema

- package-lock.json
- package.json
Bump Jest version to fix vulnerability.
> Bump Jest version to fix vulnerability

- src/container.ts
- src/context.ts
- src/facade/evaluatorFacade.ts
- src/facade/sdkFacade.ts
- src/schema/sdkFacadeSchemas.ts
- src/schema/sdkSchemas.ts
- src/sdk.ts
- src/tab.ts
- test/container.test.ts
- test/facade/sdkFacade.test.ts
- test/sdk.test.ts
- test/tab.test.ts
- test/tracker.test.ts
Add support for providing a URL sanitizer.
> Add support for providing a URL sanitizer

- src/tab.ts
- test/tab.test.ts
Prevent empty referrer from sanitization.
> Prevent empty referrer from sanitization

- src/schema/attributeSchema.ts
- src/schema/operationSchemas.ts
- src/schema/userSchema.ts
- src/validation/jsonType.ts
- test/schemas/attributesSchema.test.ts
- test/schemas/operationSchemas.test.ts
- test/validation/jsonType.test.ts
- Add schema to validate attribute names
> Add schema to validate attribute names

- src/facade/trackerFacade.ts
- src/schema/eventSchemas.ts
- src/trackingEvents.ts
- test/facade/trackerFacade.test.ts
- test/schemas/eventSchemas.test.ts
- test/tracker.test.ts
Remove TestGroupAssigned event.
> Remove TestGroupAssigned event

- src/facade/trackerFacade.ts
- src/schema/contentSchemas.ts
- src/schema/eventSchemas.ts
- src/trackingEvents.ts
- test/facade/trackerFacade.test.ts
- test/schemas/contentSchemas.test.ts
- test/schemas/eventSchemas.test.ts
- test/tracker.test.ts
Add InterestShown and PostViewed events.
> Add InterestShown and PostViewed events

- src/activeRecord.ts
- src/patch.ts
- src/schema/operationSchemas.ts
- test/activeRecord.test.ts
- test/schemas/operationSchemas.test.ts
- The new operation has been added to activeRecord.
- The new operation has been added to patch file.
- The new operation has been added to operationSchemas file.
---
I maded/updated the tests to:
- Check if a chained operation with the new operator generates a record of operations.
- Check if the operation does not throw anything when it's completed.
- Check if the operation throw a error and certain message when the path is invalid
- Check if the operation throw an error and a message when the value is not declared.
---
> Add Remove Operation

- package-lock.json
- package.json
- src/container.ts
- src/facade/sdkFacade.ts
- src/schema/sdkFacadeSchemas.ts
- src/schema/sdkSchemas.ts
- src/sdk.ts
- test/channel/sandboxChannel.test.ts
- test/channel/socketChannel.test.ts
- test/container.test.ts
- test/facade/sdkFacade.test.ts
- test/schemas/sdkFacadeSchemas.test.ts
- test/schemas/sdkSchemas.test.ts
- test/sdk.test.ts
To improve the developer experience, I propose adding a new testing: boolean option to the SDK that makes testing a breeze by:
- Replacing the `SocketChannel` with a dumb `SandboxChannel` that always confirm beacons
- Replacing the `CidAssigner` with a dumb `FixedCidAssigner` that always returns a fixed CID
With these changes, developers can fully test applications without mocks. By just registering listeners to the tracker, they can assert everything in the most reliable way once everything regarding the SDK ultimately becomes an event.
> Implement test mode

- src/facade/trackerFacade.ts
- src/schema/eventSchemas.ts
- src/tracker.ts
- src/trackingEvents.ts
- src/validation/stringType.ts
- test/facade/trackerFacade.test.ts
- test/schemas/eventSchemas.test.ts
- test/tracker.test.ts
- test/validation/stringType.test.ts
Implement link opened event.
Continuation of #116.
> Add link opened event

- .github/workflows/branch-validations.yaml
- .github/workflows/deploy-published-releases.yaml
Update workflows Node version and authentication logic
> Update workflows to use Node 16

- .github/workflows/deploy-published-releases.yaml
Fix constant substitution in the TypeScript declaration file.
> Fix constant substitution in declaration file

- .github/workflows/deploy-published-releases.yaml
- package.json
> Fix source map packaging

- src/cid/remoteAssigner.ts
- src/constants.ts
- src/contentFetcher.ts
- src/evaluator.ts
- test/cid/remoteAssigner.test.ts
- test/contentFetcher.test.ts
- test/evaluator.test.ts
Include the client version in requests to allow tracking usage metrics.
> Include client version in requests

- src/constants.ts
> Rename client library

- src/token/token.ts
- test/token/token.test.ts
Fix token serialization with UTF8 content and binary signatures.
> Fix token serialization

- .github/workflows/deploy-published-releases.yaml
- src/constants.ts
- src/container.ts
- src/contentFetcher.ts
- src/evaluator.ts
- src/facade/sdkFacade.ts
- src/schema/sdkFacadeSchemas.ts
- src/schema/sdkSchemas.ts
- src/sdk.ts
- test/container.test.ts
- test/contentFetcher.test.ts
- test/evaluator.test.ts
- test/facade/sdkFacade.test.ts
- test/schemas/sdkFacadeSchemas.test.ts
- test/schemas/sdkSchemas.test.ts
- test/sdk.test.ts
Refactor endpoint configuration to support specifying a base endpoint for all serivices.
> Refactor endpoint configuration

- package-lock.json
- package.json
> Bump @croct/json dependency

- src/token/token.ts
- test/schemas/tokenSchema.test.ts
- test/token/token.test.ts
This pull request adds new convenient methods to the `Token` class to make handling easier.
> Add new convenience token methods

- src/channel/httpBeaconChannel.ts
- src/contentFetcher.ts
- src/evaluator.ts
- src/help.ts
- test/channel/httpBeaconChannel.test.ts
- test/contentFetcher.test.ts
- test/evaluator.test.ts
- test/help.test.ts
This pull request includes help messages for evaluation and fetch errors, and also removes deprecated properties.
> Add help links and remove deprecated API

- src/contentFetcher.ts
- src/evaluator.ts
- test/contentFetcher.test.ts
- test/evaluator.test.ts
This pull request logs the region and processing time to help debug latency issues.
> Log response timing and region for debugging purposes

- src/help.ts
- test/help.test.ts
> Update help links

- src/contentFetcher.ts
- src/logging/consoleLogger.ts
This pull request includes a few changes to improve code readability and functionality in the `src` directory. The most important changes involve adding a comment to disable ESLint rules for a logging utility and minor formatting adjustments.
Code readability and functionality improvements:
* [`src/logging/consoleLogger.ts`](diffhunk://#diff-d9927206fbb4b4724534c76bc02a2cd58898e905db2b0b851be362da1808ba98R1): Added a comment to disable ESLint rules for console statements in the logging utility. (`/* eslint-disable no-console -- This is a logging utility */`)
* [`src/contentFetcher.ts`](diffhunk://#diff-ff95e402a8ee802e115b95c15250c3cf775a591aa5dc66f24fe08a5b998e6cf7L131): Removed an unnecessary blank line to improve code formatting.
> Fix code style

- tsup.config.ts
> Remove source maps
