src/validation/objectType.ts, test/validation/objectType.test.ts
Add support for object subtype validation.
=> Add support for object subtype validation

src/facade/sdkFacade.ts, src/facade/userFacade.ts, src/token/index.ts, src/tracker.ts, test/facade/sdkFacade.test.ts, test/facade/userFacade.test.ts, test/token/index.test.ts, test/tracker.test.ts
Move authentication tracking to SDK facade.
=> Move authentication tracking to SDK facade

src/schema/userSchema.ts, test/schemas/userSchema.test.ts
Change max length for custom key from 20 to 50 characters.
=> Change max length for custom key from 20 to 50 characters

src/facade/sdkFacade.ts, src/schema/sdkFacadeSchemas.ts, test/facade/sdkFacade.test.ts, test/schemas/sdkFacadeSchemas.test.ts
The need for this feature arose during the development of the playground plugin. When initializing the SDK, there is currently no easy way to either specify a token or unset any existing.
=> Allow unset any existing token on initialization

.github/workflows/deploy-published-releases.yaml, src/constants.ts
The limit is currently defined in compile time by replacing a token string with the actual value. To avoid runtime errors, the limit is specified as a string and converted in runtime to a number. This causes an error when pre-rendering SSR applications like Next.js because `window` does not exist.
=> Replace configurable max expression length with a hardcoded limit

.github/workflows/branch-validations.yaml, .github/workflows/deploy-published-releases.yaml
With the End of Life of Node 12, some dependencies are dropping support for it and building with incompatible syntax.
=> Update Node version and codeclimate action

src/schema/tokenSchema.ts, src/token/token.ts, test/schemas/tokenSchema.test.ts, test/token/token.test.ts
Fix JWT token parsing to accept `aud` as an array.
> In the general case, the `aud` value is an array of case-sensitive strings, each containing a `StringOrURI`.  In the special case when the JWT has one audience, the `aud` value MAY be a single case-sensitive string containing a `StringOrURI` value.
=> Fix JWT token parsing to accept aud as array

src/contentFetcher.ts, src/evaluator.ts, test/contentFetcher.test.ts, test/evaluator.test.ts
Node does not support `Header`, so revert to use plain object instead.
=> Use object instead of Headers

src/base64Url.ts, test/base64Url.test.ts
JWTs are UT8-encoded. This PR fixed the decode function to avoid truncating non-ASCII characters.
=> Fix decoding of UTF8-encoded tokens

src/base64Url.ts, src/token/token.ts, test/base64Url.test.ts, test/token/token.test.ts
Currently, the token incorrectly assumes the signature part of the token is UTF-8 encoded. This PR fixes this.
=> Fix token deserialization

src/contentFetcher.ts, src/evaluator.ts, test/contentFetcher.test.ts, test/evaluator.test.ts
Fix options not ignored for static content fetching and improve error reporting when the response does not include a valid JSON payload.
=> Fix fetch options and improve error reporting

.github/workflows/branch-validations.yaml, src/facade/evaluatorFacade.ts, test/facade/contentFecherFacade.test.ts, test/facade/evaluatorFacade.test.ts
The evaluation service can now extract campaign information from the page URI for improved consistency across client-side and server-side rendering.
This PR removes the campaign extraction logic to ensure consistency across libraries.
=> Remove campaign from evaluation context

src/facade/sdkFacade.ts, src/schema/sdkFacadeSchemas.ts, test/facade/sdkFacade.test.ts, test/schemas/sdkFacadeSchemas.test.ts
Prior to this PR, a new plain token was issued each time the SDK was initialized with a user ID. Whenever the user reloads the page (navigating between pages or via refresh), the SDK tracks a change in page visibility. Because the token is regenerated on each initialization, on the next page, the SDK tries to send the last pending event (`pageVisibilityChanged`) using the previous token. Then, a new connection is opened on the first event sent with the new token.
This PR changes the logic so tokens are not automatically updated when the SDK is initialized, and the same user ID is passed. In this case, if the subject of the token remains the same, it will keep the current token.
Now, passing a `userId: null` is possible to remove any existing token – the same behavior that is already …
=> Disable token refresh

package-lock.json, package.json, src/cid/assigner.ts, src/cid/cachedAssigner.ts, src/cid/remoteAssigner.ts, src/container.ts, src/facade/sdkFacade.ts, src/schema/sdkFacadeSchemas.ts, src/schema/sdkSchemas.ts, src/sdk.ts, src/trackingEvents.ts, test/cid/cachedAssigner.test.ts, test/cid/remoteAssigner.test.ts, test/container.test.ts, test/contentFetcher.test.ts, test/evaluator.test.ts, test/facade/sdkFacade.test.ts, test/schemas/contentFetcherSchemas.test.ts, test/schemas/contentSchemas.test.ts, test/schemas/contextSchemas.test.ts, test/schemas/ecommerceSchemas.test.ts, test/schemas/evaluationSchemas.test.ts, test/schemas/eventSchemas.test.ts, test/schemas/sdkFacadeSchemas.test.ts, test/schemas/sdkSchemas.test.ts, test/schemas/tokenSchema.test.ts, test/schemas/userSchema.test.ts, test/sdk.test.ts
This PR adds support for migrating from 3rd party cookies to 1st party cookies.
When passing `refreshCid: true`, the CID assigner will request a new CID even when there is a CID in the cache. Backends can then get the CID from the query string parameter and store it in cookies for later visits (overriding existing ones).
This option is recommended for a migration window only, reason why it's `false` by default. After that period, turning it off is recommended to avoid unnecessary requests.
It also improves coverage and fixes some typing issues.
=> Add support for cookie migration

src/cid/cachedAssigner.ts, src/container.ts, src/facade/sdkFacade.ts, src/schema/sdkFacadeSchemas.ts, src/schema/sdkSchemas.ts, src/sdk.ts, test/cid/cachedAssigner.test.ts, test/container.test.ts, test/facade/sdkFacade.test.ts, test/schemas/sdkFacadeSchemas.test.ts, test/schemas/sdkSchemas.test.ts, test/sdk.test.ts
Change flag `refreshCid` to `disableCidMirroring`.
=> Change flag refreshCid to disableCidMirroring

src/facade/contentFetcherFacade.ts, src/facade/sdkFacade.ts, src/schema/sdkFacadeSchemas.ts, test/facade/contentFecherFacade.test.ts, test/facade/sdkFacade.test.ts, test/schemas/sdkFacadeSchemas.test.ts
This PR introduces a new option to allow specifying a default preferred locale.
=> Add preferred locale option

src/contentFetcher.ts, src/evaluator.ts, test/contentFetcher.test.ts, test/evaluator.test.ts
This PR removes the dependency on API keys for Evaluator and Content Fetch as they require a crypto functionality not available on browsers.
=> Remove dependency on API key

src/container.ts, src/facade/sdkFacade.ts, src/schema/sdkFacadeSchemas.ts, src/schema/sdkSchemas.ts, src/sdk.ts, test/container.test.ts, test/schemas/sdkFacadeSchemas.test.ts, test/schemas/sdkSchemas.test.ts
This PR adds support for using cookies to store tokens.
=> Allow using cookies for storing preview tokens

src/contentFetcher.ts, src/evaluator.ts, test/contentFetcher.test.ts, test/evaluator.test.ts
Change `ContentFetcher` and `Evaluator` to ensure `cors` request mode when running on a browser. This is necessary for requests to include the `Origin` header[^1] (and therefore participate correctly on the CORS protocol) without relying on the security configurations of the surrounding script/page.
[^1]: https://fetch.spec.whatwg.org/#origin-header
=> Ensure requests use `cors` mode on browsers

src/cache/cookieCache.ts, test/cache/cookieCache.test.ts
This PR changes the cookies to use a `sameSite` from `strict` to `none` as it currently causes regeneration of client IDs for users accessing the application from external domains, which also affects the preview link.
=> Add cookie default options

src/container.ts, src/contentFetcher.ts, src/evaluator.ts, src/facade/sdkFacade.ts, src/schema/sdkFacadeSchemas.ts, src/schema/sdkSchemas.ts, src/sdk.ts, test/contentFetcher.test.ts, test/evaluator.test.ts, test/facade/sdkFacade.test.ts, test/schemas/sdkFacadeSchemas.test.ts, test/schemas/sdkSchemas.test.ts, test/sdk.test.ts
This PR introduces support for configuring a default global timeout, enhancing consistency across the Next.js SDK. Previously, while server-side requests could utilize a global timeout, requests made through hooks and components did not, leading to inconsistency. With this update, the global timeout setting will apply across all requests in the Next.js SDK and will be extendable to other SDKs as well. 
The default timeout is set to 5000 milliseconds (5 seconds).
=> Add support for configuring a default global timeout

src/contentFetcher.ts, src/evaluator.ts, test/evaluator.test.ts
Prevent logging a timeout when the request completes in time.
In addition to clearing the timeout for the evaluation request, I have also moved the logic to immediately follow the completion of the request. This ensures that the timeout only applies to the request logic and not to subsequent actions such as deserialization and logging.
=> Fix timeout logs

src/facade/sdkFacade.ts, test/evaluator.test.ts, test/facade/sdkFacade.test.ts
Here’s an improved version of your description:
Before this PR, passing userId as null would clear the token, even if the current token was anonymous. This caused issues for organizations with multiple applications, where some use signed tokens and others do not. For those not using signed tokens, passing null would generate an unsigned token, which lacks a token ID and initiates a new session.
With this update, the token is only regenerated if the subject changes. To retain the previous behavior, use token: null instead.
=> Change logic to preserve token

src/channel/guaranteedChannel.ts, src/channel/queuedChannel.ts, src/channel/retryChannel.ts, test/channel/guaranteedChannel.test.ts, test/channel/queuedChannel.test.ts, test/channel/retryChannel.test.ts
The current implementation of the queued channel doesn't handle failures, and that went unnoticed before because the old event tracker service just dropped invalid events. Now, with the new service, the SDK has to do the dropping. This change caused downstream channels to report errors to the upstream channel, which wasn't happening before—so this issue surfaced.
Right now, when a message fails, the queue just stops processing until a new event comes in. Since errors aren't being handled, failed messages don't get dequeued, which causes the queue to get stuck and eventually fill up.
This PR fixes that by making sure failed messages are dequeued so the next ones can still be tried.
Also, when the channel was reinitialized, you had to manually call the flush to reenqueue the messages. If …
=> Fix queued channel failure logic

src/evaluator.ts, test/evaluator.test.ts
- Assign the timer to the variable so it can be cancelled when the request is completed
- Fix testing to include the time change to avoid regressions
=> Fix incorrect timeout log on `evaluate` requests

src/channel/queuedChannel.ts, test/channel/queuedChannel.test.ts
We recently identified an issue where an application embedding a page via an iframe consistently encountered an error:
After investigation, we traced the root cause to a possible race condition: both the parent page and the iframe were accessing the same event queue concurrently. A proper fix would require a more invasive change, which involves additional planning and discussion.  
Since this is currently considered an edge case, this PR takes a minimal approach, ensuring that if a concurrent modification occurs, a message is logged but no error is thrown, allowing the SDK to continue functioning gracefully.
=> Prevent error on concurrent queue processing
